[versions]
geyser = "2.9.4-SNAPSHOT"
floodgate = "2.2.3-SNAPSHOT"
hikari = "7.0.2"
postgresql = "42.7.8"
fastutil = "8.5.2"
checker-qual = "3.21.1"

indra = "3.1.2"
paperweight = "2.0.0-beta.19"
runpaper = "3.0.1"

[libraries]
geyser-core = { module = "org.geysermc.geyser:core", version.ref = "geyser" }
floodgate-api = { group = "org.geysermc.floodgate", name = "api", version.ref = "floodgate" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }

fastutil-int-int-maps = { group = "com.nukkitx.fastutil", name = "fastutil-int-int-maps", version.ref = "fastutil" }
fastutil-int-object-maps = { group = "com.nukkitx.fastutil", name = "fastutil-int-object-maps", version.ref = "fastutil" }
fastutil-object-int-maps = { group = "com.nukkitx.fastutil", name = "fastutil-object-int-maps", version.ref = "fastutil" }
fastutil-object-object-maps = { group = "com.nukkitx.fastutil", name = "fastutil-object-object-maps", version.ref = "fastutil" }

checker-qual = { module = "org.checkerframework:checker-qual", version.ref = "checker-qual" }

[plugins]
indra = { id = "net.kyori.indra", version.ref = "indra" }
indra-publishing = { id = "net.kyori.indra.publishing", version.ref = "indra" }
indra-licenser-spotless = { id = "net.kyori.indra.licenser.spotless", version.ref = "indra" }
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
runpaper = { id = "xyz.jpenilla.run-paper", version.ref = "runpaper" }

[bundles]
fastutil = [ "fastutil-int-int-maps", "fastutil-int-object-maps", "fastutil-object-int-maps", "fastutil-object-object-maps" ]
