name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          cache-read-only: ${{ github.ref_name != 'master' && github.ref_name != 'development' }}

      - name: Archive artifact
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: GlobalLinkServer
          path: bootstrap/fabric/build/libs/GlobalLinkServer.jar
          if-no-files-found: error

      - name: Notify Discord
        if: ${{ (success() || failure()) && github.repository == 'GeyserMC/GlobalLinkServer' }}
        uses: Tim203/actions-git-discord-webhook@main
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
