name: Build and Publish

on: [ push ]

env:
  IMAGE_NAME: globallinkserver

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          cache-read-only: ${{ github.ref_name != 'master' && github.ref_name != 'development' }}

      - name: Archive Artifacts
        uses: GeyserMC/actions/upload-multi-artifact@master
        if: success()
        with:
          artifacts: |
            GlobalLinkPlugin:build/libs/GlobalLinkPlugin.jar

      - name: Notify Discord
        if: ${{ (success() || failure()) && github.repository == 'GeyserMC/GlobalLinkServer' }}
        uses: Tim203/actions-git-discord-webhook@main
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
